stages: 
  - build
  - deploy 

cache:
  untracked: true
  paths:
  - node-modules/
  - out/

prepare:
  stage: build
  script: 
    - npm install --unsafe-perm
    - sudo mkdir -p /home/public/
    - sudo mkdir -p /home/public/imgsrc/
    - sudo mkdir -p /home/public/images/
    - sudo sudo mkdir -p /home/public/images/usuarios/
    - sudo mkdir -p /home/public/images/incidencias/
    - npm run buildProduction
  tags:
    - main

start:
  stage: deploy
  script:
    - pm2 kill
    - pm2 start ecosystem.config.js --env production
  tags:
    - main
 