export { genericDelete } from './delete'
export { genericGetList } from './get-list'
export { genericGet } from './get-one'
export { genericInsert } from './insert'
export { genericPull } from './pull'
export { genericPush } from './push'
export { genericUpdate } from './update'